language:
 - python

python:
  - 3.6
  
install:
  - pip install coveralls
  - pip install flask-api
  - pip install -r requirements.txt
  
script:
  - pytest
  - coverage run --source=v1/app -m pytest && coverage report

after_success:
  - coveralls

